'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class adminhome
    
    '''<summary>
    '''lnButtonClaimsToReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonClaimsToReview As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblClaimsReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimsReview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonOverDueInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonOverDueInvoices As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblOverdueInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverdueInvoices As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonCriticalClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonCriticalClaims As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblCriticalClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCriticalClaims As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonTotalOpenClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonTotalOpenClaims As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblOpenClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenClaims As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonOverdueClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonOverdueClaims As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblOverdueClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverdueClaims As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonClaimsThisMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonClaimsThisMonth As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblClaimsThisMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimsThisMonth As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonUnassignedClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonUnassignedClaims As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblUnassignedClaims control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnassignedClaims As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButtonClaimsToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButtonClaimsToday As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblClaimsToday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClaimsToday As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnButton10DaysOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnButton10DaysOld As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbl10DaysOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl10DaysOld As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gdupdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdupdate As Global.System.Web.UI.WebControls.GridView
End Class
